AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Lambda

Metadata:
  AWS::ServerlessRepo::Application:
    Name: my-app-lambda
    Description: "SAM Template for Lambda"
    Author: user1
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['tests']
    HomePageUrl: https://github.com/ys3593/Photo-Album-Web-Application
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/ys3593/Photo-Album-Web-Application

Resources:
  searchphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos
      Description: "SAM Template for Lambda"
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          REGION: us-east-1
  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos
      Description: "SAM Template for Lambda"
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          REGION: us-east-1





